### ISSUE TITLE
Error emitted during first build in clean workspace

### ISSUE THREAD

**Issue by jamessynge** [lyft/envoy#587]
I see the error appended below. I don't know if this is just because I'm using docker for building, and is unimportant (i.e. just saying that there is no /.cache directory, will go on without it). Certainly the build seems to get to the point of running the tests without error.

@htuch Will this be resolved by switching to bazel?

```
[  4%] Building CXX object source/common/CMakeFiles/envoy-common.dir/common/hex.cc.o
The directory '/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.                                           
The directory '/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.                                                  
Collecting jinja2==2.8 (from -r configs/requirements.txt (line 1))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 2.8MB/s 
Collecting MarkupSafe (from jinja2==2.8->-r configs/requirements.txt (line 1))
  Downloading MarkupSafe-1.0.tar.gz
Installing collected packages: MarkupSafe, jinja2
  Running setup.py install for MarkupSafe ... done
Successfully installed MarkupSafe-1.0 jinja2-2.8
Traceback (most recent call last):
  File "configs/configgen.py", line 88, in <module>
    '{}/envoy_front_proxy.json'.format(sys.argv[1]), clusters=front_envoy_clusters)
  File "configs/configgen.py", line 81, in generate_config
    output = json.loads(raw_output, object_pairs_hook=OrderedDict)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[  4%] Built target envoy.generate_example_configs
```

**Comment by htuch** [comment]
This looks more like an issue in the config templating process. I don't think the Bazelification will fix, so worth investigating.

**Comment by mattklein123** [comment]
This sounds like a permission issue to me somehow (root vs. something else).

To be perfectly honest, none of us at Lyft develop with the docker image. We will have a local linux environment. I think a unified Bazel solution will make all of this a lot better.

**Comment by htuch** [comment]
This breaks for me as well. It's a regression introduced by #570, the JSON can't be parsed during config generation, since this is what the raw JSON looks like now:

```
  {
    "address": tcp://0.0.0.0:9400,
    "ssl_context": {
      "alpn_protocols": "h2,http/1.1",
      "alt_alpn_protocols": "http/1.1",
```

i.e. we're missing some quotes. I'll work on a fix and try and figure out why this wasn't caught by presubmit, since locally I have `ExampleConfigsTest.All` failing as a result.

**Comment by mattklein123** [comment]
I realized this also on the plane last night and I have a fix. @htuch I can post it if you don't already have a PR ready.
